# Generated by Django 4.0.6 on 2022-07-21 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_country_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='name_ua',
            new_name='name_uk',
        ),
    ]
