# Generated by Django 4.0.6 on 2022-07-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_name_ua_country_name_uk'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='name_ru',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='name_uk',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
