# Generated by Django 4.0.6 on 2022-07-21 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userprofile_city_userprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='surename',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telegram',
            field=models.CharField(default='', max_length=250),
        ),
    ]
