# Generated by Django 4.0.6 on 2022-07-21 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_userprofile_city_remove_userprofile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country_alias',
            field=models.CharField(default='', max_length=250),
        ),
    ]
