# Generated by Django 4.0.6 on 2022-07-22 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_cafe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='country_alias',
        ),
        migrations.AddField(
            model_name='cafe',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.citygroup'),
        ),
    ]
