# Generated by Django 4.0.6 on 2022-07-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_remove_cafe_country_alias_cafe_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='desc_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='desc_ru',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='desc_uk',
            field=models.TextField(default='', null=True),
        ),
    ]
