# Generated by Django 4.0.6 on 2022-07-22 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_cafe_desc_en_cafe_desc_ru_cafe_desc_uk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe',
            name='group',
        ),
        migrations.CreateModel(
            name='Cafe2Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.cafe')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.citygroup')),
            ],
        ),
    ]
