# Generated by Django 4.0.6 on 2022-07-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_remove_cafe_group_cafe2group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country_alias',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
