# Generated by Django 4.0.6 on 2022-07-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_city_country_alias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='alias',
        ),
    ]
