# Generated by Django 4.0.6 on 2022-07-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_remove_city_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='city',
            name='region_en',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='region_ru',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='region_uk',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
