# Generated by Django 4.0.6 on 2022-07-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_city_region_city_region_en_city_region_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='alias',
            field=models.CharField(default='', max_length=250),
        ),
    ]
