# Generated by Django 4.0.6 on 2022-07-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_city_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='prof',
            field=models.CharField(default='', max_length=250),
        ),
    ]
