# Generated by Django 4.0.6 on 2022-07-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_city_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='prof',
            field=models.CharField(default='', max_length=250),
        ),
    ]
