# Generated by Django 4.0.6 on 2022-07-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_userprofile_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='prof_en',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prof_ru',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prof_uk',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='publicname_en',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='publicname_ru',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='publicname_uk',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
