# Generated by Django 4.0.6 on 2022-08-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_userprofile_prof_en_userprofile_prof_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
    ]
