# Generated by Django 4.0.6 on 2022-08-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_city_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cafe',
            name='address_en',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='address_ru',
            field=models.TextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='address_uk',
            field=models.TextField(default='', null=True),
        ),
    ]
