# Generated by Django 4.0.6 on 2022-07-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=250)),
                ('name_en', models.CharField(default='', max_length=250, null=True)),
                ('name_ru', models.CharField(default='', max_length=250, null=True)),
                ('name_uk', models.CharField(default='', max_length=250, null=True)),
            ],
        ),
    ]
